### ISSUE TITLE
chatserver process killed unexpectedly.

### ISSUE THREAD

**Issue by astroshim** [astroshim/thunder-chat#1]

**Comment by astroshim** [comment]
```
[root@ip-172-31-18-135 thunder-chat]# gdb ChatServer core.7434
GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-30.amzn2.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ChatServer...(no debugging symbols found)...done.
BFD: Warning: /home/ec2-user/thunder-chat/core.7434 is truncated: expected core file size >= 149655552, found: 52944896.
[New LWP 7445]
[New LWP 7448]
[New LWP 7441]
[New LWP 7444]
[New LWP 7439]
[New LWP 7440]
[New LWP 7442]
[New LWP 7443]
[New LWP 7447]
[New LWP 7449]
[New LWP 7446]
[New LWP 7434]
Cannot access memory at address 0x7f90fc97a108
Cannot access memory at address 0x7f90fc97a100
Failed to read a valid object file image from memory.
Core was generated by `./ChatServer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043d9f3 in ChatServer::MessageBroadcast(BroadcastMessage*) ()
[Current thread is 1 (LWP 7445)]
(gdb)
(gdb) bt
#0  0x000000000043d9f3 in ChatServer::MessageBroadcast(BroadcastMessage*) ()
#1  0x0000000000439ecb in ThreadBroadcaster::Run() ()
#2  0x0000000000438563 in HandlerRunner(void*) ()
#3  0x00007f90fc53d54b in ?? ()
#4  0x0000000000000000 in ?? ()
```

**Comment by astroshim** [comment]
mutex 로 해결
